### ISSUE TITLE
Danish not recognized

### ISSUE THREAD

**Issue by LuigiImVector** [EbookFoundation/free-programming-books-search#29]
I was trying to use fpb.json to improve my telegram bot (EbookFoundation/free-programming-books#6263) and I noticed an anomaly, there is an element with no language:
```json
{
  "language": {},
  "index": {},
  "sections": [
    {
       "section": "C",
       "entries": [
          {
             "url": "https://web.archive.org/web/20190701062226/http://artcreationforever.com/bgnet.html",
             "title": "Beej's Guide til Netvarksprogrammierung",
```

The problem is that on free-programming-books this file is called `free-programming-books-dk` but on the [languages.js](https://github.com/EbookFoundation/free-programming-books-parser/blob/main/languages.js) the Danish is equal to `da`.

I didn't create a PR to rename the file because I don't know which language code to use; [ISO 639-2 list](https://www.loc.gov/standards/iso639-2/php/code_list.php) says that the code of Danish language is `da`.

---

Using the search the resources are there, although with some resources writing the full title does not find them, you have to delete a few characters, for example:
- `Object-oriented Programming in C#`: you have to delete `in C#`
- `Objektorienteret programmering i Java`: you have to delete `ava`

Obviously without `language.code` value the result is: 
![image](https://user-images.githubusercontent.com/59611597/178154156-f1bf1e32-b802-41cf-af56-b87f8d9158a0.png)

**Comment by davorpa** [comment]
Danish full ICU locale code is `da-dk`

da: language
dk: country

https://www.localeplanet.com/icu/da-DK/index.html

so should be renamed in fpb

**Comment by LuigiImVector** [comment]
let's wait for a response from @brogan20

**Comment by brogan20** [comment]
As far as I can tell the file in fpb should be `da` as it is recognized as such in the site David listed [here](https://www.localeplanet.com/icu/iso639.html#da) and also in the resource listed by ImVector. `da-DK` is the language code for Danish specifically in Denmark. The problem could be temporarily fixed in fpb-search by changing the code in languages.json to `dk` until the filename in fpb is changed

**Comment by davorpa** [comment]
Solved. See PR EbookFoundation/free-programming-books#6909
